spring:
  application:
    name: businessassistant-login
  jmx:
    enabled: true

server:
  port: 8761

management:
  endpoints:
    web:
      exposure:
        include: "*"

---
security:
  datasource:
    signUpUrl: /v1/api/login
    secret: SgVkYp3s6v9y$B&E)H+MbQeThWmZq4t7
    headerString: Authorization
    tokenPrefix: Bearer 
    authorities: authorities
    err: Auth Error, Token Unavailable

---
logging:
  level:
    "[org.springframework]": ERROR
    "[com.businessassistantbcn]": INFO
  pattern:
  # console: Spring's default
    file: "%date %5level %-40.40logger{39} [%thread] %msg%n"
#  file:
#    name: login.log
